### ISSUE TITLE
问题样例以及说明

### ISSUE THREAD

**Issue by Groupsun** [Groupsun/CCPA-2020-LAB#1]
可以在这里详细说明你遇到了什么问题，还可以附带一些文件或者图片进行说明，并且支持markdown格式。尽量使得每个issue都附上对应的标签方便查找，我也能方便的分类查看：
- PyHCL-env: 有关设置PyHCL环境相关的问题，包括firrtl的问题；
- OS-env: 和操作系统有关的问题；
- simulation-env: 配置仿真工具方面相关的问题；
- Lab: 实验本身的问题；
之后我会根据大家提的问题再多加更多的标签，如果暂时找不到好的标签可以不加。

**Comment by ForTheFreedom** [comment]
师兄，问一下这个语句Emitter.dumpVerilog(Emitter.dump(Emitter.emit(HalfAdder()),
"HalfAdder.fir"))生成的文件在哪个地方呢

**Comment by Groupsun** [comment]
> 师兄，问一下这个语句Emitter.dumpVerilog(Emitter.dump(Emitter.emit(HalfAdder()),
> "HalfAdder.fir"))生成的文件在哪个地方呢

请直接创建一个新的issue，这个只是说明样例。我在那里回答你的问题。
