### ISSUE TITLE
sbt compile和sbt test报错

### ISSUE THREAD

**Issue by hzx718** [Groupsun/CCPA-2020-LAB#10]
运行sbt compile和sbt test的时候都会出现下面的报错，请问该如何解决呢
![1](https://user-images.githubusercontent.com/40926654/82120233-3ad3f480-97b7-11ea-8b8b-2dfa3cacbf18.png)
![Uploading 2.png…]()

**Comment by hzx718** [comment]
好像依旧报错
![image](https://user-images.githubusercontent.com/40926654/82123066-dd956e80-97c9-11ea-8f61-c713dcd813e3.png)

**Comment by Groupsun** [comment]
这个错误我也没见过，我查了后这里所讲的情况与你的相似，你可以参考一下：
https://blog.csdn.net/rain_web/article/details/105493068

**Comment by hzx718** [comment]
现在不报错了，但是又回到卡sbt compile的情况了....

**Comment by Groupsun** [comment]
就是下载又变慢了吗？上面这种解决方法不会把源换回去吧？

**Comment by hzx718** [comment]
看群里的记录又换了一个源，现在终于可以了，谢谢助教

**Comment by Groupsun** [comment]
> 看群里的记录又换了一个源，现在终于可以了，谢谢助教
可以把源也贴在这里，做个记录吧。

**Comment by hzx718** [comment]
https://blog.csdn.net/dwryuan/article/details/56015168
