### ISSUE TITLE
sbt assembly遇到错误

### ISSUE THREAD

**Issue by lisanzhu** [Groupsun/CCPA-2020-LAB#12]
我遇到了这个错误，请问该怎么解决
![187801589692474_ pic_hd](https://user-images.githubusercontent.com/57362255/82136417-8d0d2800-9840-11ea-9516-e6450895d8fe.jpg)

**Comment by Groupsun** [comment]
根据截图显示的问题是出在你没有足够的权限访问`firrtl.jar`，我推测你的firrtl文件夹是放在了系统目录下而不是用户目录下。建议把firrtl文件夹放在用户目录下可以省去很多不必要的麻烦。另外有同学也提出过相关的问题，可以参考：https://github.com/Groupsun/CCPA-2020-LAB/issues/7#issue-619370646

**Comment by lisanzhu** [comment]
> 根据截图显示的问题是出在你没有足够的权限访问`firrtl.jar`，我推测你的firrtl文件夹是放在了系统目录下而不是用户目录下。建议把firrtl文件夹放在用户目录下可以省去很多不必要的麻烦。另外有同学也提出过相关的问题，可以参考：[#7 (comment)](https://github.com/Groupsun/CCPA-2020-LAB/issues/7#issue-619370646)

好的，解决了，谢谢您
