### ISSUE TITLE
firrtl配置问题

### ISSUE THREAD

**Issue by Grace-919** [Groupsun/CCPA-2020-LAB#14]
![image](https://user-images.githubusercontent.com/65445962/82137954-0875d600-984f-11ea-8718-f9b6ae7c3ba9.png)
![image](https://user-images.githubusercontent.com/65445962/82137959-1d526980-984f-11ea-9d89-c8c4d3a22330.png)
![image](https://user-images.githubusercontent.com/65445962/82137963-24797780-984f-11ea-8ddb-321df50a4106.png)
sbt assembly有生成文件，配置好环境，但是firrtl --help出错

**Comment by Groupsun** [comment]
PATH路径有问题，应该是：`/home/grace/firrtl/utils/bin:$PATH`

**Comment by Grace-919** [comment]
谢谢，已经改好了。



---原始邮件---
发件人: "Sunny Chen"<notifications@github.com&gt;
发送时间: 2020年5月17日(周日) 下午3:05
收件人: "Groupsun/CCPA-2020-LAB"<CCPA-2020-LAB@noreply.github.com&gt;;
抄送: "Grace-919"<2539631746@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Groupsun/CCPA-2020-LAB] firrtl配置问题 (#14)




 
PATH路径有问题，应该是：/home/grace/firrtl/utils/bin:$PATH
