### ISSUE TITLE
clone firrtl速度太慢

### ISSUE THREAD

**Issue by zzy-lab** [Groupsun/CCPA-2020-LAB#15]
![221bfcf86c0fc89b647dae640355b33](https://user-images.githubusercontent.com/60964331/82138675-d7989f80-9854-11ea-93ae-b44dc0604e20.png)
好像停在这里好久都不动了

**Comment by Groupsun** [comment]
如果下载的太慢了，就使用群里我上传的文件，是一样的。

**Comment by zzy-lab** [comment]
怎么把文件拉进ubuntu中啊？安装了vmware tool 也重启过了

**Comment by Groupsun** [comment]
直接ctrl+c和ctrl+v应该都可以了。如果不行的话可以考虑用共享文件夹。
