### ISSUE TITLE
cocotb can't find simulator when make file

### ISSUE THREAD

**Issue by ac108** [Groupsun/CCPA-2020-LAB#17]
![test](https://user-images.githubusercontent.com/51014199/82148273-e0ee3000-9885-11ea-8b71-2d038bbe122c.jpg)

**Comment by Groupsun** [comment]
没有配置好verilator，你安装了verilator了吗。

**Comment by Fruit-Shrimp** [comment]
我这也出现了一样的问题
![微信截图_20200520132329](https://user-images.githubusercontent.com/52727094/82408198-b4146580-9a9d-11ea-8b8f-9b936a6d6185.png)
问题有解决ma
