### ISSUE TITLE
NameError: name 'Module' is not defined

### ISSUE THREAD

**Issue by Grace-919** [Groupsun/CCPA-2020-LAB#18]
![image](https://user-images.githubusercontent.com/65445962/82167672-209d3200-98ef-11ea-8c84-f4398f5e6829.png)
 程序运行之后一直提示：
class HalfAdder (Module)
NameError: name "Module" is not defined

**Comment by Groupsun** [comment]
你要把pyhcl源码包放在你项目的根目录下，并`from pyhcl import *`。

**Comment by Grace-919** [comment]
> 项目的根目录下，并from pyhcl import *

![image](https://user-images.githubusercontent.com/65445962/82169460-2a756400-98f4-11ea-9796-f98500ca4a5e.png)
这样放置pychl吗？但是还是有问题

**Comment by Groupsun** [comment]
你需要把`pyhcl2`下面的`pyhcl`文件夹放在根目录下才行，这个才是源码包。

**Comment by Grace-919** [comment]
> 你要把pyhcl源码包放在你项目的根目录下，并from pyhcl import *。
![image](https://user-images.githubusercontent.com/65445962/82169614-92c44580-98f4-11ea-88aa-80aacadf7105.png)
后来把pyhcl源码包放在项目的根目录（如上图）也不行。
最后重新建立.py文件，就可以了。
原来一直出错是因为开始的时候将文件建立在venv目录下了
