### ISSUE TITLE
配置环境变量时遇到的问题

### ISSUE THREAD

**Issue by hzx718** [Groupsun/CCPA-2020-LAB#19]
如图，请问为什么目录下文件明明存在，但是添加环境变量s时缺显示不存在呢

![1](https://user-images.githubusercontent.com/40926654/82197905-1e0dfd00-992e-11ea-80a2-7984c788f9e9.png)
![2](https://user-images.githubusercontent.com/40926654/82197913-2108ed80-992e-11ea-999e-751d64739269.png)

**Comment by Groupsun** [comment]
`export PATH=/home/huangzixi/firrtl/utils/bin:$PATH`

**Comment by hzx718** [comment]
好的，谢谢助教
