### ISSUE TITLE
环境配置关闭终端后失效

### ISSUE THREAD

**Issue by CPJ31415** [Groupsun/CCPA-2020-LAB#22]
<img width="960" alt="微呜" src="https://user-images.githubusercontent.com/52948345/82276239-468e0980-99b7-11ea-9667-adb87370aa7f.png">
<img width="960" alt="我去" src="https://user-images.githubusercontent.com/52948345/82276252-4db51780-99b7-11ea-8020-4d454e30501f.png">

我应该是配置好了，如第一张图。但是我关闭终端再打开就变成第二章图的样子了。然后再添加，又好了，关闭再打开又没了。

<img width="406" alt="洒洒水" src="https://user-images.githubusercontent.com/52948345/82276477-f82d3a80-99b7-11ea-9d02-fad3c0bec903.png">
 
但是这个environment里面一直都有这个路径

**Comment by CPJ31415** [comment]
@Groupsun

**Comment by Groupsun** [comment]
你是使用了修改`/etc/environment`的方法是吗？这种方式似乎会有一点问题，之前也有同学问过我类似的问题，这种方法修改后似乎会被`/etc/profile`里面的内容覆盖掉。
要永久生效的话，最好使用修改`/etc/profile`或者`~/.bashrc`的方式。

**Comment by CPJ31415** [comment]
路径的确出错了。重启后一直循环在输入密码的登陆界面。用Ctrl + Alt + F3 打开后，想通过vim /ect/proflie 修改路径。但是vim指令没找到，sudo的指令也没有找到。请问这个怎么解决？
@Groupsun

**Comment by CPJ31415** [comment]
重启后一直循环在输入密码的登陆界面，用Ctrl + Alt + F3打开后，想通过vim / ect / proflie修改路径。但是vim指令没找到，sudo的指令也没有找到。请问这个怎么解决？ @Groupsun

**Comment by Groupsun** [comment]
`vim`是一个终端用的文本编辑器，你需要安装：`sudo apt-get install vim`

**Comment by CPJ31415** [comment]
但是sudo :command no found

**Comment by Groupsun** [comment]
> 但是sudo :command no found

不是很明白你的意思，如果你已经在root用户下，那就不用`sudo`了。

**Comment by CPJ31415** [comment]
就是, 因为路径改了。登不进去，我就用Ctrl + Alt + F3 打开。输入 vim 想改路径，提示no found。我也试了getit，也是no found。最后我想要sudo vim，也是command no found

**Comment by Groupsun** [comment]
那你可能是这种情况，你看看这里：https://blog.csdn.net/qq_26442553/article/details/79183260
