### ISSUE TITLE
关于自行仿真验证其正确性的要求

### ISSUE THREAD

**Issue by sinceseto** [Groupsun/CCPA-2020-LAB#23]
练习里要求自行仿真验证其正确性。
请问是否要验证所有情况？
比如有模块有n个bit输入，是否需要枚举2^n次？
那这样harness有点难写，比如4位全加器需要写8个循环嵌套？

**Comment by Groupsun** [comment]
有两种方法。

## 方法1

你现在写的模块的IO口应该是类似下面的这种结构：

```python
# a、b是输入的四位二进制数，cout是最高位的进位输出
io = IO(
    a0 = Input(U.w(1)),
    a1 = Input(U.w(1)),
    # ...
    s0 = Output(U.w(1)),
    s1 = Output(U.w(1)),
    # ...
    cout = Output(U.w(1))
)
```

这种情况下，在测试文件中可以使用这种方式来构造：首先，你定义一个变量如`inc`初始值为0，让它每次循环都自增1，最大到15。接着，准备一个数组大小为4，将`inc`转化为用该数组表示的二进制数，并将对应的值赋给对应的输入口：

```C++
// 规定数组bin当中bin[0]为最高位，bin[3]为最低位
char bin[4];

void dec2bin(char num)
{
    for(int i = 0;i < 4;i++)
    {
        bin[3-i] = num % 2;
        num = num / 2;
    }
}

/*
 * 在while循环中的代码：
 * <module_name>.io_a0 = bin[3]
 * <module_name>.io_a1 = bin[2]
 * ...
 */
```

四位二进制数a和b都可以这样来构造。而结果则可以通过将二进制数：(cout, s3, s2, s1, s0)转化成十进制数来观察结果正确性。

## 方法2

在后面我会提到PyHCL还提供了一种用法，可以将电路实体（如输入输出口、寄存器、Wire）中的某个位提取出来，所以你还可以这么写：

```python
io = IO(
    a=Input(U.w(4)),
    b=Input(U.w(4)),
    cout=Output(U.w(1))
)
```

接着，将输入口的每一位提取出来输入到每个子全加器当中：

```python
fc0 = FullAdder()
fc0.io.a <<= io.a[0]
fc0.io.b <<= io.b[0]
# 以此类推
```

这样子你可以省去仿真的时候转化的麻烦而直接将熟知输入到对应的IO口即可。
