### ISSUE TITLE
在同一个模块中有io.y0<<=io.x0语句，为何运行时产生不了.v文件呢，只会产生.fir文件

### ISSUE THREAD

**Issue by ForTheFreedom** [Groupsun/CCPA-2020-LAB#25]

**Comment by Groupsun** [comment]
请提供更多的信息，提供出错代码以及错误信息。

**Comment by ForTheFreedom** [comment]
Exception in thread "main" firrtl.passes.CheckInitialization$RefNotInitializedException:  : [module Power]  Reference io is not fully initialized.
   : io.y1 <= VOID

io = IO(
    x0=Input(U.w(1)),
    x1=Input(U.w(1)),
    x2=Input(U.w(1)),
    y0=Output(U.w(1)),
    y1=Output(U.w(1)),
    y2=Output(U.w(1)),
    y3=Output(U.w(1)),
    y4=Output(U.w(1)),
    y5=Output(U.w(1)))
    # 填充完整输出端⼝s以及cout的逻辑，例如：
    io.y0<<=io.x0
    io.y2<<=(~io.x0)&io.x1
    io.y3<<=io.x0&(io.x1^io.x2)
    io.y4<<=(~io.x1)&io.x2
    io.y5<<=io.x1&io.x2

**Comment by Groupsun** [comment]
你的输出端口y1没有赋值
