### ISSUE TITLE
vscode无法创建文件和文件夹

### ISSUE THREAD

**Issue by hzx718** [Groupsun/CCPA-2020-LAB#27]
如图，使用vscode创建文件或者文件下时会出现如下报错
![image](https://user-images.githubusercontent.com/40926654/82335509-044ae380-9a1c-11ea-961c-d41069322336.png)
![image](https://user-images.githubusercontent.com/40926654/82335552-16c51d00-9a1c-11ea-82f1-836114dfc457.png)
在vscode打开的文件夹目录如下
![image](https://user-images.githubusercontent.com/40926654/82335717-4ffd8d00-9a1c-11ea-88e5-17efd6873e7b.png)

**Comment by Groupsun** [comment]
你创建的这个文件没有vs code没有权限写。检查该文件夹的权限情况以及你打开vs code的用户情况。

**Comment by hzx718** [comment]
好的，谢谢助教
