### ISSUE TITLE
运行实验报错

### ISSUE THREAD

**Issue by ZoeDong** [Groupsun/CCPA-2020-LAB#32]
在运行实验的时候pycharm报错sh: 1: firrtl not found ，是在用户目录下执行的，也重启过虚拟机还是不行
![image](https://user-images.githubusercontent.com/60535303/82683080-f2b74500-9c82-11ea-9a8c-b99b783a7c0b.png)

环境变量感觉也没有问题
![image](https://user-images.githubusercontent.com/60535303/82683369-82f58a00-9c83-11ea-80df-a8bf39970cf2.png)

**Comment by ZoeDong** [comment]
可以生成.fir文件 但是运行.py文件还是会报错

**Comment by Groupsun** [comment]
报什么错误

**Comment by ZoeDong** [comment]
和第一张图一样还是 sh: 1: firrtl not found

**Comment by Groupsun** [comment]
那为什么可以生成`.fir`文件。同学能不能把你的问题说明的详细点。

**Comment by ZoeDong** [comment]
不太清楚为什么会这样，我新建一个项目后新建一个python file，把实验内容复制进去运行，就可以生成.fir文件但是下方也会报错sh: 1: firrtl not found，不管是重启还是重新生成一个新项目都是既可以生成.fir文件也会报错
![image](https://user-images.githubusercontent.com/60535303/82722600-c3441f00-9cfa-11ea-9b7b-3ac55b38893f.png)

**Comment by Groupsun** [comment]
你参考一下这个issue吧：https://github.com/Groupsun/CCPA-2020-LAB/issues/13

**Comment by ZoeDong** [comment]
请问添加环境变量是在Run->Edit Configurations->Environment variables把PATH添加进去吗？如果是的话尝试过清除缓存和添加环境变量，但是都没有效果。但是又确实是能够生成.fir文件所以不太明白这个报错到底有没有影响，运行后界面是这样的。

![image](https://user-images.githubusercontent.com/60535303/82736389-fb2f7e80-9d5b-11ea-9335-760467b9cf20.png)
