### ISSUE TITLE
如何使用自定义模块？

### ISSUE THREAD

**Issue by KaranaLJX** [Groupsun/CCPA-2020-LAB#34]
实验一完成的半加器和全加器应该怎么级联呢?

**Comment by Groupsun** [comment]
https://github.com/Groupsun/CCPA-2020-LAB/blob/master/Chapter%201%20%E7%A1%AC%E4%BB%B6%E7%94%B5%E8%B7%AF%E8%AE%BE%E8%AE%A1%E5%9F%BA%E7%A1%80.md#%E6%A8%A1%E5%9D%97%E5%B1%82%E6%AC%A1
