### ISSUE TITLE
是否需要提交代码，如何提交

### ISSUE THREAD

**Issue by sinceseto** [Groupsun/CCPA-2020-LAB#35]
请问是否需要提交代码？
如果需要提交代码，是以什么方式提交，是放报告里还是放文件夹里？
pyhcl代码和harness代码都要提交吗？

**Comment by Groupsun** [comment]
提交pyhcl代码、仿真代码和波形文件

**Comment by sinceseto** [comment]
请问能不能每次实验给出提交的规范？

**Comment by Groupsun** [comment]
往后每次实验都需要提交这些文件。
