### ISSUE TITLE
关于选择器输出的逻辑问题

### ISSUE THREAD

**Issue by Grace-919** [Groupsun/CCPA-2020-LAB#38]
设计2-4选择器的时候，输出只能选择两路
![image](https://user-images.githubusercontent.com/65445962/83346432-dd12e100-a34e-11ea-9f2c-b06c036c0343.png)
![image](https://user-images.githubusercontent.com/65445962/83346463-1cd9c880-a34f-11ea-889a-49f6a11f36e1.png)
![image](https://user-images.githubusercontent.com/65445962/83346467-26633080-a34f-11ea-954e-4f74548b23d6.png)

**Comment by Groupsun** [comment]
`&`是按位与，不是逻辑与
