### ISSUE TITLE
关于clock没有时钟变化（即一直为低电位的问题）

### ISSUE THREAD

**Issue by ForTheFreedom** [Groupsun/CCPA-2020-LAB#39]
![image](https://user-images.githubusercontent.com/49015378/83401691-f3489c00-a437-11ea-9185-5a59afff157b.png)

**Comment by Groupsun** [comment]
你的仿真文件有做好时钟吗？你需要在仿真里面定义好时钟。

**Comment by ForTheFreedom** [comment]
我看pdf上讲的是clock时钟是默认的，所以没有去管clock，是要在harness文件里面自己设置clock数据啊？

**Comment by Groupsun** [comment]
是的，我在提供的verilator的例子里面也有其他的测试文件包含如何设置时钟的例子。而第0章也提供了在cocotb当中的时钟设置的例子。
