### ISSUE TITLE
关于安装openjdk时遇到的问题

### ISSUE THREAD

**Issue by hzx718** [Groupsun/CCPA-2020-LAB#4]
运行指令sudo apt-get install default-jdk时，出现了以下错误：
请问该如何解决
![QQ图片20200515000219](https://user-images.githubusercontent.com/40926654/81957547-4dc3b900-963f-11ea-9928-77035eb506cc.png)

**Comment by Groupsun** [comment]
涉及到使用apt安装jdk发生错误的话，我推荐直接从官网上下载压缩包的方法并配置环境变量来安装。你可以参考：https://blog.csdn.net/gatieme/article/details/52723931，这里面的3.3.2节通过bin包的方式安装。
如果你必须使用apt的方式来安装的话，可以考虑安装openjdk，在上面的文章当中也有相应的教程。这里还有一篇可供参考：https://www.jianshu.com/p/61c546bb77e1。
