### ISSUE TITLE
关于代码具体行为的问题

### ISSUE THREAD

**Issue by sinceseto** [Groupsun/CCPA-2020-LAB#40]
```
cnt = RegInit(U.w(32)(0))
with when(a):
	cnt <<= cnt+U(1)
with when(b):
	cnt <<= cnt-U(1)
```
想问一下这种代码的具体行为，比如假如a与b条件同时成立时的cnt的行为？
是否要保证在所有情况下cnt只有一条连接语句？

**Comment by Groupsun** [comment]
`a`与`b`同时成立的时候，cnt将会赋予`cnt-U(1)`的值

**Comment by sinceseto** [comment]
请问是不是每个with语句最终会转化成对其中每个左值的<<=语句。
是不是意味着对于一个左值来说，只有最后一个包含它的with语句是有效的。

**Comment by Groupsun** [comment]
如果一个左值在同一个语句块当中被前后赋值，那么它以最后一次赋值为准。
含有条件语句的时候，同一个条件分支下同一个左值被多次赋值，也是以最后一次赋值为准。
如果最后转化成的条件同时成立，如上图所示，可能会是以最后一个语句为准；写代码的时候尽量保证每个条件都是分立的，不要产生交集。

**Comment by sinceseto** [comment]
```
ra = Reg(U.w(32))
rb = Reg(U.w(32))
rc = Reg(U.w(32))
ra <<= rb
rb <<= rc
```
请问这样的代码在一次上升沿后，具体数据的流向

**Comment by Groupsun** [comment]
rc上一个时钟周期的值写入到rb当中，rb上一个时钟周期的值写入到ra当中；
且，自己做个实验看看波形，也可以看出来。
