### ISSUE TITLE
关于FIFO的要求问题

### ISSUE THREAD

**Issue by TEF-47** [Groupsun/CCPA-2020-LAB#41]
FIFO是否允许同时读取写入，以及读取时是否会删除队列头的数据？
FIFO中要求的生存周期四个时钟周期是指能在器件存在四个周期吗？

**Comment by Groupsun** [comment]
都可以。你可以实现成同时读写，也可以实现成同一个时钟周期不能同时读写；
生存周期四个时钟周期也就是说在这个数据如果一直没有被弹出，则它只能够生存4个时钟周期，超过4个时钟周期后就会被清除。

**Comment by TEF-47** [comment]
读取时是否会删除队列头的数据

**Comment by Groupsun** [comment]
自行决定，可以删除也可以不删除，只要在**外部**的行为就是一个队列即可；这个模块和面向对象非常相似，对用户来说它就是一个黑盒子。
