### ISSUE TITLE
pyhcl使用

### ISSUE THREAD

**Issue by Grace-919** [Groupsun/CCPA-2020-LAB#46]
![image](https://user-images.githubusercontent.com/65445962/83967527-e2df6800-a8f4-11ea-92df-3cdb81138e93.png)
![image](https://user-images.githubusercontent.com/65445962/83967532-f4287480-a8f4-11ea-8990-879040d23e93.png)
运行时 reg.io.sin <<= io.value总是显示Exception: type does not match

**Comment by Groupsun** [comment]
看群记录，我曾发过勘误。
