### ISSUE TITLE
sbt compile指令长时间没回应

### ISSUE THREAD

**Issue by RedLotus-jpg** [Groupsun/CCPA-2020-LAB#5]
![QQ图片20200515030830](https://user-images.githubusercontent.com/57861271/81975286-62ad4600-9659-11ea-9872-9b1f90dc3abc.png)
这个好像停在这很久了，怎么处理，有没有影响的。
![QQ图片20200515031133](https://user-images.githubusercontent.com/57861271/81975555-cf284500-9659-11ea-994b-6209f1ea6715.png)
另外sbt test指令中途会kill，跳了一连串的warn出来，同问。

**Comment by Groupsun** [comment]
sbt compile长时间没有回应，上面是由于配置sbt下载速度太慢了，需要你更换sbt源来处理，注意不是apt源是sbt源，教程可以参照：https://www.jianshu.com/p/8b4609d57f0a
后者中途会kill掉，是因为你虚拟机划分的内存太小了，建议将内存划到4G来执行。

**Comment by RedLotus-jpg** [comment]
> sbt编译没有持续响应，上面是由于配置sbt下载速度太慢了，需要你更换sbt源来处理，注意不是aptsource是sbt源，教程可以参照：[https](https://www.jianshu.com/p/8b4609d57f0a) ://www.jianshu.com/p/ [8b4609d57f0a](https://www.jianshu.com/p/8b4609d57f0a)
> 附件中途会kill掉，是因为你虚拟机划分的内存太小了，建议将内存划到4G来执行。

![QQ图片20200515205225](https://user-images.githubusercontent.com/57861271/82052326-07796300-96ee-11ea-9ffa-0a3d2df8ce25.png)
这个应该算是装好了吧，但却找不到sbt目录。

**Comment by RedLotus-jpg** [comment]
> sbt编译没有持续响应，上面是由于配置sbt下载速度太慢了，需要你更换sbt源来处理，注意不是aptsource是sbt源，教程可以参照：[https](https://www.jianshu.com/p/8b4609d57f0a) ://www.jianshu.com/p/ [8b4609d57f0a](https://www.jianshu.com/p/8b4609d57f0a)
> 附件中途会kill掉，是因为你虚拟机划分的内存太小了，建议将内存划到4G来执行。

![QQ图片20200515205225](https://user-images.githubusercontent.com/57861271/82052973-1f9db200-96ef-11ea-980b-352c8c99d111.png)
这个样子应该算是装好了吧，但是我无法找到sbt目录。

**Comment by Groupsun** [comment]
> > sbt编译没有持续响应，上面是由于配置sbt下载速度太慢了，需要你更换sbt源来处理，注意不是aptsource是sbt源，教程可以参照：[https](https://www.jianshu.com/p/8b4609d57f0a) ://www.jianshu.com/p/ [8b4609d57f0a](https://www.jianshu.com/p/8b4609d57f0a)
> > 附件中途会kill掉，是因为你虚拟机划分的内存太小了，建议将内存划到4G来执行。
> 
> ![QQ图片20200515205225](https://user-images.githubusercontent.com/57861271/82052973-1f9db200-96ef-11ea-980b-352c8c99d111.png)
> 这个样子应该算是装好了吧，但是我无法找到sbt目录。

只要你执行`sbt assembly`成功就行了，你进入/utils/bin，执行`./firrtl --help`试试看有没有出错，如果问题的话就可以了。接着把`<你所放在的路径>/firrtl/utils/bin`加入到环境变量当中即可。

**Comment by RedLotus-jpg** [comment]
> > > sbt编译没有持续响应，上面是由于配置sbt下载速度太慢了，需要你更换sbt源来处理，注意不是aptsource是sbt源，教程可以参照：[https](https://www.jianshu.com/p/8b4609d57f0a) ://www.jianshu.com/p/ [8b4609d57f0a](https://www.jianshu.com/p/8b4609d57f0a)
> > > 附件中途会kill掉，是因为你虚拟机划分的内存太小了，建议将内存划到4G来执行。
> > 
> > 
> > ![QQ图片20200515205225](https://user-images.githubusercontent.com/57861271/82052973-1f9db200-96ef-11ea-980b-352c8c99d111.png)
> > 这个样子应该算是装好了吧，但是我无法找到sbt目录。
> 
> 只要你执行`sbt assembly`成功就行了，你进入/utils/bin，执行`./firrtl --help`试试看有没有出错，如果问题的话就可以了。接着把`<你所放在的路径>/firrtl/utils/bin`加入到环境变量当中即可。

![QQ图片20200515221106](https://user-images.githubusercontent.com/57861271/82059733-07329500-96f9-11ea-91c7-81672357ce1a.png)
![QQ图片20200515221111](https://user-images.githubusercontent.com/57861271/82059741-0863c200-96f9-11ea-94ae-2dd31bf4ee74.png)
这样就算是没问题了吗

**Comment by Groupsun** [comment]
> 
> ![QQ图片20200515221106](https://user-images.githubusercontent.com/57861271/82059733-07329500-96f9-11ea-91c7-81672357ce1a.png)
> ![QQ图片20200515221111](https://user-images.githubusercontent.com/57861271/82059741-0863c200-96f9-11ea-94ae-2dd31bf4ee74.png)
> 这样就算是没问题了吗

是的，接下来添加进环境变量当中即可。

**Comment by lisanzhu** [comment]
> > ![QQ图片20200515221106](https://user-images.githubusercontent.com/57861271/82059733-07329500-96f9-11ea-91c7-81672357ce1a.png)
> > ![QQ图片20200515221111](https://user-images.githubusercontent.com/57861271/82059741-0863c200-96f9-11ea-94ae-2dd31bf4ee74.png)
> > 这样就算是没问题了吗
> 
> 是的，接下来添加进环境变量当中即可。

你好，请问一下我怎么将他添加进环境变量的时候不好用了，可是我已经将其加入其中了

**Comment by Groupsun** [comment]
> 你好，请问一下我怎么将他添加进环境变量的时候不好用了，可是我已经将其加入其中了

同学能不能更详细的描述你的问题，提供一些结果图片之类的。

**Comment by lisanzhu** [comment]
![B82EF967EC5BA96B358B91315A2E4494](https://user-images.githubusercontent.com/57362255/82118555-bd09ec00-97aa-11ea-9d56-7f83cc724c36.jpg)
![1DDA32123431EF9694951382D9CE7BB4](https://user-images.githubusercontent.com/57362255/82118559-bf6c4600-97aa-11ea-966d-3c8affeb85aa.jpg)
请您看一下谢谢啦

**Comment by Groupsun** [comment]
你描述的问题于本issue问题无关，我帮你独立开一个新的issue来参考：https://github.com/Groupsun/CCPA-2020-LAB/issues/9
