### ISSUE TITLE
函数式定义的模块如何实例化或者生成.fir文件

### ISSUE THREAD

**Issue by SmallPeaches** [Groupsun/CCPA-2020-LAB#50]
在这次实验的FIR滤波器中使用的是def定义一个函数的方法来实现一个滤波器，那在最后一句`Emitter.dumpVerilog(Emitter.dump(Emitter.emit(???), "firfilter.fir"))`生成.fir文件的代码的???那里要怎么写。
如果我想使用不同width的滤波器，要怎么调用`firfilter`函数来实例化呢？
麻烦老师了

**Comment by Groupsun** [comment]
```python
def firfilter(width: int):
    class FirFilter(Module):
        pass
    return FirFilter()

Emitter.dumpVerilog(Emitter.dump(Emitter.emit(firfilter()), "firfilter.fir"))
```
