### ISSUE TITLE
sbt publishLocal 报错

### ISSUE THREAD

**Issue by Fruit-Shrimp** [Groupsun/CCPA-2020-LAB#6]
### sbt publishLocal出现error
![微信截图_20200516112013](https://user-images.githubusercontent.com/52727094/82109315-7ba41d00-9767-11ea-9f70-a8dd9faac860.png)
sbt assembly等其他的都能成功运行

**Comment by Groupsun** [comment]
安装流程里面这一步是非必须的，只需要你`sbt assembly`执行成功即可。

**Comment by Fruit-Shrimp** [comment]
奥奥谢谢助教
