### ISSUE TITLE
Command 'sbt' not found

### ISSUE THREAD

**Issue by Faye1999** [Groupsun/CCPA-2020-LAB#7]
已经安装了sbt
![image](https://user-images.githubusercontent.com/57753090/82109781-587b6c80-976b-11ea-895f-e24667558b6d.png)

然后配置到环境中
![image](https://user-images.githubusercontent.com/57753090/82109798-88c30b00-976b-11ea-96e9-e1bf621e8b06.png)

但是执行sbt compile的时候出现 Command 'sbt' not found 
请问是什么问题呢？
![ZB9P~N)QINCKU{RI7T(M5R1](https://user-images.githubusercontent.com/57753090/82109834-c7f15c00-976b-11ea-9b3d-7998328cf50f.png)

**Comment by Groupsun** [comment]
你在添加环境变量之后，是否有执行`source`命令？你可以使用`echo $PATH`来查看环境变量是否生效了。如果都不是上述这些问题的话，可以考虑重新启动终端、重新登录用户以及重启的方式解决。

**Comment by Faye1999** [comment]
执行过source命令，环境变量应该没问题
![image](https://user-images.githubusercontent.com/57753090/82110893-f5420800-9773-11ea-96c6-45886c818944.png)

执行sbt的时候，会出现Permission denied
![image](https://user-images.githubusercontent.com/57753090/82110938-29b5c400-9774-11ea-9f17-ce5b06a2baad.png)

试过这样添加权限，还是不行
![image](https://user-images.githubusercontent.com/57753090/82110974-4c47dd00-9774-11ea-983a-49768c106d13.png)

不知道是不是哪里的权限出了问题？

**Comment by Faye1999** [comment]
已经解决了...
把sbt解压到用户目录下就没问题

还是感谢助教！！

**Comment by Groupsun** [comment]
你可以尝试用sudo执行sbt，如果你把sbt放在了系统目录下；不过你已经ok了就没什么问题。
还有些同学会遇到执行sbt命令权限不足的原因，有些是因为你的firrtl目录放在了系统目录下，这里建议firrtl目录统一放在用户目录下。
