### ISSUE TITLE
clone  firrtl时RPC失败

### ISSUE THREAD

**Issue by hzx718** [Groupsun/CCPA-2020-LAB#8]
按照GitHub教程上安装firrtl，运行命令git clone https://github.com/freechipsproject/firrtl.git && cd firrtl出现以下问题，请问该如何解决
![9ed80c3a047fab411138e7b37113d97](https://user-images.githubusercontent.com/40926654/82113391-40661600-9788-11ea-9095-05c2d313d5fa.png)

**Comment by Groupsun** [comment]
你可以尝试执行下面的命令后再克隆：
```shell
git config --global http.postBuffer 524288000
```
如果问题依旧的话，可以考虑改成用ssh的方式来克隆。
这个问题可能是因为firrtl比较大，curl的postBuffer默认值太小的原因。
你还可以参照：
https://blog.csdn.net/IT_liuchengli/article/details/77040806

**Comment by hzx718** [comment]
> 你可以尝试执行以下的命令后再克隆：
> 
> ```shell
> git config --global http.postBuffer 524288000
> ```
> 
> 如果问题依旧的话，可以考虑改成用ssh的方式来克隆。
> 这个问题可能是因为firrtl比较大，curl的postBuffer值太小的原因。
> 你还可以参照：[https](https://blog.csdn.net/IT_liuchengli/article/details/77040806) : //blog.csdn.net/
> [IT_六成里/文章/细节/ 77040806](https://blog.csdn.net/IT_liuchengli/article/details/77040806)

已经解决了，谢谢助教

**Comment by hzx718** [comment]
> git config --global http.postBuffer 524288000
> ```
> 
> 如果问题依旧的话，可以考虑改成用ssh的方式来克隆。
> 这个问题可能是因为firrtl比较大，curl的postBuffer值太小的原因。
> 你还可以参照：[https](https://blog.csdn.net/IT_liuchengli/article/details/77040806) : //blog.csdn.net/
> [IT_六成里/文章/细节/ 77040806](https://blog.csdn.net/IT_liuchengli/article/details/77040806)

已经解决了，谢谢助教

**Comment by Groupsun** [comment]
如果解决了先别close吧，我担心某些不会用的同学会不知道已经解决了的issue会被转移到closed里面，issue默认界面会过滤掉close了的。

**Comment by hzx718** [comment]
不好意思，没看清楚，以为是关闭评论....




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sunny Chen"<notifications@github.com&gt;; 
发送时间: 2020年5月16日(星期六) 下午4:29
收件人: "Groupsun/CCPA-2020-LAB"<CCPA-2020-LAB@noreply.github.com&gt;; 
抄送: "子嘿"<1098341923@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Groupsun/CCPA-2020-LAB] clone  firrtl时遇到的问题 (#8)





 
如果解决了先别close吧，我担心某些不会用的同学会不知道已经解决了的issue会被转移到closed里面，issue默认界面会过滤掉close了的。
