### ISSUE TITLE
firrtl环境变量配置问题

### ISSUE THREAD

**Issue by Groupsun** [Groupsun/CCPA-2020-LAB#9]
original from: https://github.com/Groupsun/CCPA-2020-LAB/issues/5#issuecomment-629630642

> ![B82EF967EC5BA96B358B91315A2E4494](https://user-images.githubusercontent.com/57362255/82118555-bd09ec00-97aa-11ea-9d56-7f83cc724c36.jpg)
> ![1DDA32123431EF9694951382D9CE7BB4](https://user-images.githubusercontent.com/57362255/82118559-bf6c4600-97aa-11ea-966d-3c8affeb85aa.jpg)
> 请您看一下谢谢啦

**Comment by Groupsun** [comment]
可以使用`echo $PATH`来验证环境变量有没有配置成功，而且推荐使用添加到`~/.bashrc`或者`/etc/profile`等方法来添加环境变量。
https://blog.csdn.net/White_Idiot/article/details/78253004

**Comment by lisanzhu** [comment]
> 可以使用`echo $PATH`来验证环境变量有没有配置成功，而且推荐使用添加到`~/.bashrc`或者`/etc/profile`等方法来添加环境变量。
> https://blog.csdn.net/White_Idiot/article/details/78253004

好的谢谢您，我想要请问一下，在Mac中使用brew来安装sbt为什么下载好慢，一个多小时也是没有增长多少，请问这个是什么原因呢。
![image](https://user-images.githubusercontent.com/57362255/82122021-91473000-97c3-11ea-981f-a5e32c8c1485.png)

**Comment by Groupsun** [comment]
> 好的谢谢您，我想要请问一下，在Mac中使用brew来安装sbt为什么下载好慢，一个多小时也是没有增长多少，请问这个是什么原因呢。
> ![image](https://user-images.githubusercontent.com/57362255/82122021-91473000-97c3-11ea-981f-a5e32c8c1485.png)

brew在国内用由于不可抗力因素会很慢，可以换中科大的源来解决：https://lug.ustc.edu.cn/wiki/mirrors/help/brew.git

**Comment by lisanzhu** [comment]
> > 好的谢谢您，我想要请问一下，在Mac中使用brew来安装sbt为什么下载好慢，一个多小时也是没有增长多少，请问这个是什么原因呢。
> > ![image](https://user-images.githubusercontent.com/57362255/82122021-91473000-97c3-11ea-981f-a5e32c8c1485.png)
> 
> brew在国内用由于不可抗力因素会很慢，可以换中科大的源来解决：https://lug.ustc.edu.cn/wiki/mirrors/help/brew.git

好的，谢谢您
